import { Address } from '@/services/fhir-service/resources/types/Address';
import { Attachment } from '@/services/fhir-service/resources/types/Attachment';
import { CodeableConcept } from '@/services/fhir-service/resources/types/CodeableConcept';
import { Coding } from '@/services/fhir-service/resources/types/Coding';
import { ContactPoint } from '@/services/fhir-service/resources/types/ContactPoint';
import { Element } from '@/services/fhir-service/resources/types/Element';
import { HumanName } from '@/services/fhir-service/resources/types/HumanName';
import { Identifier } from '@/services/fhir-service/resources/types/Identifier';
import { Meta } from '@/services/fhir-service/resources/types/Meta';
import { Period } from '@/services/fhir-service/resources/types/Period';
import { Reference } from '@/services/fhir-service/resources/types/Reference';
import { Signature } from '@/services/fhir-service/resources/types/Signature';

export interface Extension extends Element {
    url: string;
    _url?: Element;
    valueAddress?: Address;
    valueAttachment?: Attachment;
    valueBase64Binary?: string;
    _valueBase64Binary?: Element;
    valueBoolean?: boolean;
    _valueBoolean?: Element;
    valueCanonical?: string;
    _valueCanonical?: Element;
    valueCode?: string;
    _valueCode?: Element;
    valueCodeableConcept?: CodeableConcept;
    valueCoding?: Coding;
    valueContactPoint?: ContactPoint;
    valueDate?: string;
    _valueDate?: Element;
    valueDateTime?: string;
    _valueDateTime?: Element;
    valueDecimal?: number;
    _valueDecimal?: Element;
    valueHumanName?: HumanName;
    valueId?: string;
    _valueId?: Element;
    valueIdentifier?: Identifier;
    valueInstant?: string;
    _valueInstant?: Element;
    valueInteger?: number;
    _valueInteger?: Element;
    valueMarkdown?: string;
    _valueMarkdown?: Element;
    valueMeta?: Meta;
    valueOid?: string;
    _valueOid?: Element;
    valuePeriod?: Period;
    valuePositiveInt?: number;
    _valuePositiveInt?: Element;
    valueRange?: Range;
    valueReference?: Reference;
    valueSignature?: Signature;
    valueString?: string;
    _valueString?: Element;
    valueTime?: string;
    _valueTime?: Element;
    valueUnsignedInt?: number;
    _valueUnsignedInt?: Element;
    valueUri?: string;
    _valueUri?: Element;
    valueUrl?: string;
    _valueUrl?: Element;
    valueUuid?: string;
    _valueUuid?: Element;
}

